export const ItemMap = [
	{
		header: 'The road to school',
		type: 'web development, datavis, storytelling',
		text: '<p>  an interactive visualization about how the Syrian conflict is stopping millions of children from going to school</p>Overall, this was the most productive and busiest month of 2016 for me, and also the most rewarding. I left Zurich filled with new knowledge, experiences, ways of thinking and exposure to the most important facets of data visualization and interaction design. I will be missing every single member of this team, and I am very excited to see what 2017 has in store for them and myself. Things will be creative!',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'responsive d3.js charts',
		type: 'web development',
		text: '<p>contribution to visualization library for the website of the city of Zurich</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'photography',
		type: 'personal project',
		text: '<p>I use film (Fujicolor 200 is my go-to choice) and carry a small point-and-shoot Olympus XA in my bag. </p><p>Instead of snapping a photo with my phone, I do it with my small film camera - a way to teach my eyes to not be so hungry to see the result right away.</p> – <br> <a href="http://cargocollective.com/kallirroi" target="_blank">link</a><br> <a href="http://velveteyes.net/features/kalli-retzepi/" target="_blank">feature #1 </a> | <a href="http://www.c41magazine.it/kalli-retzepi-goes-find-light/" target="_blank">feature #2</a> | <a href="http://www.thisiswander.com/post/157453662292/kalli-retzepi-boston-usa-zurich-switzerland" target="_blank">feature #3</a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.' ,
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'thoughtless acts',
		type: 'photography + design thinking',
		text: '<p>This project, inspired by the book of Jane Fulton Suri of IDEO titled "Thoughtless Acts", is an exercise in seeing rather than looking at the different types of interactions we engage in with our surroundings.</p> – <br> <a href="http://cargocollective.com/kallirroi/thoughtless-acts" target="_blank">link</a> I enjoy both the process of changing how I see the world around me, as well as the process of building new behaviors. My aim is to turn this exercise into a habit. I want to keep on documenting how we are eternally interacting with our surroundings in different ways, no matter how familiar we are with them. Being a bit of a nomad like myself, I see this as a great opportunity in developing such a habit and hopefully start building a body of work that can speak about the people and their thoughtless acts across places and identities. I have a feeling that we are not too different from each other!',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'p5.js',
		type: 'creative coding',
		text: '<p> just experimenting with the javascript version of Processing</p> – <br> <a href="http://cargocollective.com/kallirroi/generative-code" target="_blank">link</a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'samtous.wtf',
		type: 'web design',
		text: '<a href="http://samtous.wtf/" target="_blank"> samtous.wtf </a>  <br> a restless portfolio as an archive of images</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'The evolution of AI',
		type: 'web design',
		text: '<a href="https://www.ubs.com/microsites/artificial-intelligence/en/new-dawn.html" target="_blank"> the evolution of AI  </a>  <p>collaboration for a visual storytelling project about the future of AI</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'EXPLORA',
		type: 'web design',
		text: '<a href="https://www.explora.ethz.ch/" target="_blank"> EXPLORA </a> <p> collaboration for a visual storytelling project on behalf of the ETH Library</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'archmix.es ',
		type: 'web design',
		text: '<a href="http://archmix.es/" target="_blank"> archmix.es </a> <p>tweeting from your couch, in your sweats, can be an architectural act</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'birthday cake robot ',
		type: 'for fun',
		text: '<p> A friend designed a cake decoration machine that sprays edible food dye onto a cake, and demo-ed it at a birthday party. I created the front and back-end of a web application that collected birthday messages which were then spray painted on the cakes frosting, in real time. I designed and implemented the messaging service for the machine: a mobile-only web app, whose UI was simulating a keypad that party participants can access from their phones and send birthday greetings. This was happening in real time, with people texting wishes from all over the world. The user entered their initials and then their birthday message using the on-screen buttons.</p>',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	},
	{
		header: 'master thesis',
		type: 'about',
		text: '<p> My Master thesis demonstrates the feasibility of identifying, retrieving and analyzing for research purposes data from clinical MRI scans acquired in patients with chronic focal pain diagnoses. A computerized brain model as well as morphometric indices were generated for each patient.</p> <p>I collected patient medical information and identified cohorts of interest using the Research Patient Data Registry (RPDR) at Massachusetts General Hospital (MGH). RPDR is a centralized clinical data registry, or data warehouse. It gathers data from various hospital legacy systems and stores it in one place. Researchers access this data with user-defined queries for aggregate patient totals and, with proper IRB approval, obtain detailed clinical data. It is composed of over 4.5 million patients and over one billion records from patient encounters, labs and results, and other medical care. I used the medical diagnostic codes (ICD-9) to identify patients diagnosed with Migraine, or any migraine variant. Querying the above database returns a group of tables with patient information (.txt format) which are related to each other with a unique patient identifier number. I used SQLite in order to easily access and query across all of these tables, which in total were more than 100"000 rows. </p>',
		links:'<a href="lab.interactivethings.com/road-to-school/" target="_blank">link</a>'
	}
];	
