export const ItemMap = [
	{
		name: 'about',
		text: '<p> My name is Kallirroi; many people call me Kalli. I explore the space found at the intersection of design, engineering, science and images.</p>  <p>In my free time I run long distances, read, write, photograph, and have espresso-fueled debates, often about politics.</p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'datavis',
		text: '<p><a href="https://lab.interactivethings.com/road-to-school/" target="_blank"> the road to school </a> <br> an interactive visualization about how the Syrian conflict is stopping millions of children from going to school</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'datavis',
		text: '<p>responsive d3.js charts </a> <br> contribution to visualization library for the website of the city of Zurich</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'photography',
		text: '<p>I use film (Fujicolor 200 is my go-to choice) and carry a small point-and-shoot Olympus XA in my bag. </p><p>Instead of snapping a photo with my phone, I do it with my small film camera - a way to teach my eyes to not be so hungry to see the result right away.</p> – <br> <a href="http://cargocollective.com/kallirroi" target="_blank">link</a><br> <a href="http://velveteyes.net/features/kalli-retzepi/" target="_blank">feature #1 </a> | <a href="http://www.c41magazine.it/kalli-retzepi-goes-find-light/" target="_blank">feature #2</a> | <a href="http://www.thisiswander.com/post/157453662292/kalli-retzepi-boston-usa-zurich-switzerland" target="_blank">feature #3</a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.' 
	},
	{
		name: 'thoughtless acts',
		text: '<p>This project, inspired by the book of Jane Fulton Suri of IDEO titled "Thoughtless Acts", is an exercise in seeing rather than looking at the different types of interactions we engage in with our surroundings.</p> – <br> <a href="http://cargocollective.com/kallirroi/thoughtless-acts" target="_blank">link</a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'creative code',
		text: '<p> p5.js  </p> <p> just experimenting with the javascript version of Processing</p> – <br> <a href="http://cargocollective.com/kallirroi/generative-code" target="_blank">link</a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'web design',
		text: '<p><a href="http://samtous.wtf/" target="_blank"> samtous.wtf </a> <br> a restless portfolio as an archive of images</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'web design',
		text: '<p><a href="https://www.ubs.com/microsites/artificial-intelligence/en/new-dawn.html" target="_blank"> the evolution of AI  </a> <br> collaboration for a visual storytelling project about the future of AI</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'web design',
		text: '<p><a href="https://www.explora.ethz.ch/" target="_blank"> EXPLORA </a> <br> collaboration for a visual storytelling project on behalf of the ETH Library</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	},
	{
		name: 'web design',
		text: '<p><a href="http://archmix.es/" target="_blank"> archmix.es </a> <br> tweeting from your couch, in your sweats, can be an architectural act</p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante arcu, aliquam sed sagittis at, consequat vitae nunc. Morbi tristique, mi in ultricies cursus, quam risus fringilla metus, quis tempor magna mi nec massa. Nunc pulvinar mi et tortor tincidunt, ullamcorper sagittis mi feugiat. Aliquam at volutpat augue, a lobortis augue. Praesent eget venenatis lacus. Quisque pretium ante ac metus viverra, vel mollis nisi malesuada. Morbi tincidunt enim velit. Pellentesque vel diam tristique, hendrerit mauris eu, malesuada libero. Maecenas eleifend ex ante, vitae posuere sem faucibus eget. Pellentesque at enim nec eros malesuada consequat sit amet facilisis diam. Pellentesque dignissim porta augue sit amet vestibulum. Integer sagittis erat eu euismod pharetra. Pellentesque lacinia tellus vitae arcu porta, nec ultricies libero auctor. Ut placerat vulputate tincidunt. In pharetra dignissim lectus, eget lobortis libero laoreet a. Ut sodales metus nec ipsum iaculis, nec consectetur ipsum porttitor.'
	}
];	
